<a href="https://colab.research.google.com/github/BhanuPrakash-Guniganti/python-for-ml/blob/main/9_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
data = {
    "CGPA": [8.2, 7.1, 6.4, 9.0, 5.8, 7.5, 8.7, 6.9, 7.0, 8.1, 5.9, 9.2, 6.6, 7.8, 8.4],

    "Internships": [2, 1, 0, 3, 0, 2, 2, 1, 2, 0, None, 4, 1, 2, 3],

    "Aptitude_score": [78, 65, 55, 88, 45, 72, 81, 60, None, 77, 50, 90, 58, 69, 82],

    "Communication_skills": [7, 6, 5, 8, 4, 6, 7, 6, 5, 7, 4, 9, 5, 6, 8],

    "Projects": [3, 2, 1, 4, 0, 2, 3, 2, 1, 3, 1, 5, 2, 2, 3],

    "Placed": ["Yes", "Yes", "No", "Yes", "No", "Yes", "Yes", "No",
               "Yes", "No", "Yes", "No", "Yes", "Yes", "Yes"]
}

In [39]:
import pandas as pd

In [40]:
frame=pd.DataFrame(data)

In [41]:
frame

    CGPA  Internships  Aptitude_score  Communication_skills  Projects Placed
0    8.2          2.0            78.0                     7         3    Yes
1    7.1          1.0            65.0                     6         2    Yes
2    6.4          0.0            55.0                     5         1     No
3    9.0          3.0            88.0                     8         4    Yes
4    5.8          0.0            45.0                     4         0     No
5    7.5          2.0            72.0                     6         2    Yes
6    8.7          2.0            81.0                     7         3    Yes
7    6.9          1.0            60.0                     6         2     No
8    7.0          2.0             NaN                     5         1    Yes
9    8.1          0.0            77.0                     7         3     No
10   5.9          NaN            50.0                     4         1    Yes
11   9.2          4.0            90.0                     9         5     No
12   6.6          1.0            58.0                     5         2    Yes
13   7.8          2.0            69.0                     6         2    Yes
14   8.4          3.0            82.0                     8         3    Yes

In [42]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CGPA                  15 non-null     float64
 1   Internships           14 non-null     float64
 2   Aptitude_score        14 non-null     float64
 3   Communication_skills  15 non-null     int64
 4   Projects              15 non-null     int64
 5   Placed                15 non-null     object
dtypes: float64(3), int64(2), object(1)
memory usage: 852.0+ bytes

In [43]:
frame.isnull().sum()

CGPA                    0
Internships             1
Aptitude_score          1
Communication_skills    0
Projects                0
Placed                  0
dtype: int64

In [44]:
frame.columns

Index(['CGPA', 'Internships', 'Aptitude_score', 'Communication_skills',
       'Projects', 'Placed'],
      dtype='object')

In [45]:
frame['Internships']

0     2.0
1     1.0
2     0.0
3     3.0
4     0.0
5     2.0
6     2.0
7     1.0
8     2.0
9     0.0
10    NaN
11    4.0
12    1.0
13    2.0
14    3.0
Name: Internships, dtype: float64

In [46]:
frame['Internships'] =frame['Internships'].fillna(frame['Internships'].median())

In [47]:
frame['Internships']

0     2.0
1     1.0
2     0.0
3     3.0
4     0.0
5     2.0
6     2.0
7     1.0
8     2.0
9     0.0
10    2.0
11    4.0
12    1.0
13    2.0
14    3.0
Name: Internships, dtype: float64

In [48]:
frame['Aptitude_score']

0     78.0
1     65.0
2     55.0
3     88.0
4     45.0
5     72.0
6     81.0
7     60.0
8      NaN
9     77.0
10    50.0
11    90.0
12    58.0
13    69.0
14    82.0
Name: Aptitude_score, dtype: float64

In [49]:
frame

    CGPA  Internships  Aptitude_score  Communication_skills  Projects Placed
0    8.2          2.0            78.0                     7         3    Yes
1    7.1          1.0            65.0                     6         2    Yes
2    6.4          0.0            55.0                     5         1     No
3    9.0          3.0            88.0                     8         4    Yes
4    5.8          0.0            45.0                     4         0     No
5    7.5          2.0            72.0                     6         2    Yes
6    8.7          2.0            81.0                     7         3    Yes
7    6.9          1.0            60.0                     6         2     No
8    7.0          2.0             NaN                     5         1    Yes
9    8.1          0.0            77.0                     7         3     No
10   5.9          2.0            50.0                     4         1    Yes
11   9.2          4.0            90.0                     9         5     No
12   6.6          1.0            58.0                     5         2    Yes
13   7.8          2.0            69.0                     6         2    Yes
14   8.4          3.0            82.0                     8         3    Yes

In [50]:
frame.isnull().sum()

CGPA                    0
Internships             0
Aptitude_score          1
Communication_skills    0
Projects                0
Placed                  0
dtype: int64

In [51]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CGPA                  15 non-null     float64
 1   Internships           15 non-null     float64
 2   Aptitude_score        14 non-null     float64
 3   Communication_skills  15 non-null     int64
 4   Projects              15 non-null     int64
 5   Placed                15 non-null     object
dtypes: float64(3), int64(2), object(1)
memory usage: 852.0+ bytes

In [52]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [53]:
frame['Placed']=le.fit_transform(frame['Placed'])

In [54]:
frame

    CGPA  Internships  Aptitude_score  Communication_skills  Projects  Placed
0    8.2          2.0            78.0                     7         3       1
1    7.1          1.0            65.0                     6         2       1
2    6.4          0.0            55.0                     5         1       0
3    9.0          3.0            88.0                     8         4       1
4    5.8          0.0            45.0                     4         0       0
5    7.5          2.0            72.0                     6         2       1
6    8.7          2.0            81.0                     7         3       1
7    6.9          1.0            60.0                     6         2       0
8    7.0          2.0             NaN                     5         1       1
9    8.1          0.0            77.0                     7         3       0
10   5.9          2.0            50.0                     4         1       1
11   9.2          4.0            90.0                     9         5       0
12   6.6          1.0            58.0                     5         2       1
13   7.8          2.0            69.0                     6         2       1
14   8.4          3.0            82.0                     8         3       1

In [55]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CGPA                  15 non-null     float64
 1   Internships           15 non-null     float64
 2   Aptitude_score        14 non-null     float64
 3   Communication_skills  15 non-null     int64
 4   Projects              15 non-null     int64
 5   Placed                15 non-null     int64
dtypes: float64(3), int64(3)
memory usage: 852.0 bytes

In [56]:
from re import X
# Feature engineering (input & Output mapping)

# x=frame[['CGPA', 'Internships', 'Aptitude_score', 'Communication_skills', 'Projects']]
x=frame.drop(columns=['Placed']) #input
y=frame['Placed'] #output

In [57]:
x

    CGPA  Internships  Aptitude_score  Communication_skills  Projects
0    8.2          2.0            78.0                     7         3
1    7.1          1.0            65.0                     6         2
2    6.4          0.0            55.0                     5         1
3    9.0          3.0            88.0                     8         4
4    5.8          0.0            45.0                     4         0
5    7.5          2.0            72.0                     6         2
6    8.7          2.0            81.0                     7         3
7    6.9          1.0            60.0                     6         2
8    7.0          2.0             NaN                     5         1
9    8.1          0.0            77.0                     7         3
10   5.9          2.0            50.0                     4         1
11   9.2          4.0            90.0                     9         5
12   6.6          1.0            58.0                     5         2
13   7.8          2.0            69.0                     6         2
14   8.4          3.0            82.0                     8         3

In [58]:
y

0     1
1     1
2     0
3     1
4     0
5     1
6     1
7     0
8     1
9     0
10    1
11    0
12    1
13    1
14    1
Name: Placed, dtype: int64

In [59]:
#data modelling
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [60]:
y_test

9     0
11    0
0     1
Name: Placed, dtype: int64

In [61]:
x_train

    CGPA  Internships  Aptitude_score  Communication_skills  Projects
13   7.8          2.0            69.0                     6         2
5    7.5          2.0            72.0                     6         2
8    7.0          2.0             NaN                     5         1
2    6.4          0.0            55.0                     5         1
1    7.1          1.0            65.0                     6         2
14   8.4          3.0            82.0                     8         3
4    5.8          0.0            45.0                     4         0
7    6.9          1.0            60.0                     6         2
10   5.9          2.0            50.0                     4         1
12   6.6          1.0            58.0                     5         2
3    9.0          3.0            88.0                     8         4
6    8.7          2.0            81.0                     7         3

In [62]:
x_test

    CGPA  Internships  Aptitude_score  Communication_skills  Projects
9    8.1          0.0            77.0                     7         3
11   9.2          4.0            90.0                     9         5
0    8.2          2.0            78.0                     7         3

In [63]:
from sklearn.linear_model import LogisticRegression

In [69]:
model = LogisticRegression()
model.fit(x_train, y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
y_pred = model.predict(x_test)